# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "Gpt Free Prompt"
SPDX-PackageSupplier = "Sami Finnilä <sami.finnila@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/gptfreeprompt"

[[annotations]]
path = ["package-lock.json", "package.json", "composer.json", "composer.lock", "psalm-baseline.xml", "psalm.xml", "tests/stub.phpstub"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Sami Finnilä <sami.finnila@nextcloud.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["l10n/**.js", "l10n/**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nextcloud translators <https://www.transifex.com/nextcloud/>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
